# Name of the executable
EXE=qplot
########################
# The Files:
TOOLBASE = GCContent  GenomeRegionSeqStats QSamFlag Sequence BamQC QCStats
SRCONLY=main.cpp
HDRONLY=FlagDef.h

USER_COMPILE_VARS = -lcrypto

########################
# Include the base Makefile
PARENT_MAKE = Makefile.src
include ../Makefile.inc

########################
# Add any additional targets here.
